[package]
name = "playlist_manager"
version = "0.1.0"
authors = ["Maxwell L-T <maxwell.lt@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
tempfile = "3.1.0"
cursive = "0.15"
